# application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopmart-app
  namespace: argocd # This manifest must be deployed in the argocd namespace
spec:
  project: default
  source:
    # The SSH URL for your PRIVATE manifests repository
    repoURL: 'git@github.com:your-github-aashishrrjp/shopmart-k8s.git'
    targetRevision: HEAD
    path: . # Deploy manifests from the root of the repository
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: shopmart-prod # Deploy the app into this namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true # Argo CD will create the 'shopmart-prod' namespace if it doesn't exist